# /// script
# requires-python = ">=3.11"
# ///
"""Write COSTS.md from usage.jsonl (one line per paid Gemini call) and rates.json (prices).

usage: uv run tools/costs.py      # from the project root
"""
import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WORK = {"tts": "narration", "listen": "listening judge", "genvideo": "b-roll"}
COLUMNS = ["Date", "Work", "Model", "Calls", "Failed", "Tokens in", "Tokens out", "Video s", "Estimate"]


def load():
    rates_path, log_path = ROOT / "rates.json", ROOT / "usage.jsonl"
    if not rates_path.exists():
        sys.exit(f"no rates file: write {rates_path} from the pricing page "
                 "(README.md, \"COSTS.md: the cost estimate\")")
    rates = json.loads(rates_path.read_text())
    lines = log_path.read_text().splitlines() if log_path.exists() else []
    return rates, [json.loads(line) for line in lines if line.strip()]


def rate_for(table, modality):
    """USD per 1M tokens: one number for every modality, or a {modality: rate} table."""
    if isinstance(table, (int, float)):
        return table
    return (table or {}).get(modality)


def price(call, rates, unpriced):
    """The call's estimated USD; anything without a rate is added to `unpriced` and costs 0."""
    model = rates["models"].get(call["model"])
    if model is None:
        unpriced.add(f"{call['model']}: no entry")
        return 0.0
    if "per_second" in model:
        if model["per_second"] is None:
            unpriced.add(f"{call['model']}: per_second")
            return 0.0
        return model["per_second"] * (call.get("seconds") or 0)
    usage = call.get("usage") or {}
    parts = [("input", m, n) for m, n in usage.get("input", {}).items()]
    parts += [("output", m, n) for m, n in usage.get("output", {}).items()]
    if usage.get("thought"):
        parts.append(("output", "text", usage["thought"]))  # thinking is billed as text output
    cost = 0.0
    for direction, modality, tokens in parts:
        rate = rate_for(model.get(direction), modality)
        if rate is None:
            unpriced.add(f"{call['model']}: {direction} {modality}")
        else:
            cost += rate * tokens / 1e6
    return cost


def group(calls, rates, unpriced):
    """One row per day, workstream and model."""
    rows = defaultdict(lambda: {"calls": 0, "failed": 0, "in": 0, "out": 0, "seconds": 0.0, "cost": 0.0})
    for call in calls:
        row = rows[(call["time"][:10], WORK.get(call["script"], call["script"]), call["model"])]
        usage = call.get("usage") or {}
        row["calls"] += 1
        row["failed"] += 0 if call.get("ok", True) else 1
        row["in"] += sum(usage.get("input", {}).values())
        row["out"] += sum(usage.get("output", {}).values()) + usage.get("thought", 0)
        row["seconds"] += call.get("seconds") or 0
        row["cost"] += price(call, rates, unpriced)
    return rows


def table(rows):
    cells = [COLUMNS] + [[date, work, model, str(r["calls"]), str(r["failed"]), f"{r['in']:,}",
                          f"{r['out']:,}", f"{r['seconds']:.1f}" if r["seconds"] else "",
                          f"${r['cost']:.3f}"] for (date, work, model), r in sorted(rows.items())]
    widths = [max(len(row[i]) for row in cells) for i in range(len(COLUMNS))]

    def fmt(row):
        return "| " + " | ".join(c.ljust(w) for c, w in zip(row, widths)) + " |"

    return [fmt(cells[0]), fmt(["-" * w for w in widths])] + [fmt(row) for row in cells[1:]]


def main():
    rates, calls = load()
    unpriced = set()
    rows = group(calls, rates, unpriced)
    by_work = defaultdict(float)
    for (_, work, _), r in rows.items():
        by_work[work] += r["cost"]
    total = sum(by_work.values())
    split = ", ".join(f"{work} ${cost:.2f}" for work, cost in sorted(by_work.items()))
    out = ["# Cost estimate", "",
           "Generated by `tools/costs.py` from `usage.jsonl` and `rates.json`; do not edit by hand.",
           f"Rates from {rates.get('source', '?')}, read {rates.get('read', '?')}. "
           "Token counts are the ones the API returned for each call.", "",
           f"**Total: ${total:.2f}**" + (f" ({split})" if split else ""), ""] + table(rows)
    if unpriced:
        out += ["", "## Unpriced", "", "Counted as $0 until `rates.json` has a rate:", ""]
        out += [f"- {item}" for item in sorted(unpriced)]
    (ROOT / "COSTS.md").write_text("\n".join(out) + "\n")
    print(f"COSTS.md: {len(calls)} calls, total ${total:.2f}" + (f" ({split})" if split else ""))
    for item in sorted(unpriced):
        print(f"unpriced: {item}", file=sys.stderr)


if __name__ == "__main__":
    main()
